### ISSUE TITLE
Not working with Android Studio Giraffe

### ISSUE THREAD

**Issue by wixeless** [gektor650/OkHttpProfiler-AndroidStudio-Plugin#8]
macOS: 13.5 (22G74)

Android Studio Giraffe | 2022.3.1

Build #AI-223.8836.35.2231.10406996, built on June 29, 2023

plugin version: 1.0.17

Caused by: java.lang.ClassNotFoundException: com.android.tools.idea.logcat.AndroidLogcatService PluginClassLoader(plugin=PluginDescriptor(name=OkHttp Profiler, id=com.itkacher.okhttpprofiler, descriptorPath=plugin.xml, path=~/Library/Application Support/Google/AndroidStudio2022.3/plugins/OkHttpProfiler, version=1.0.17, package=null, isBundled=false), packagePrefix=null, instanceId=109, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:217)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 59 more

**Comment by yash10019coder** [comment]
I may have a hunch on this why this is failing 
the `AndroidLogcatService` class is probably depreciated or removed from the AS giraffe so we may need to migrate to `LogcatService`.

I tired but not able to find any documentation or reference on these classes.
![image](https://github.com/gektor650/OkHttpProfiler-AndroidStudio-Plugin/assets/76404817/55d78fef-e7ab-4833-adfa-eb126eb3a3bd)

**Comment by eugene-tkachenko** [comment]
Fixed :) 
https://plugins.jetbrains.com/plugin/11249-okhttp-profiler/versions/stable/373734
It will take several dates to complete the JetBrains review, so you can install it manually (you can download the zip file from the link above).
